# See https://pre-commit.com for more information
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    # See https://pre-commit.com/hooks
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.3
    hooks:
        # Run the linter.
        - id: ruff
          args: [--fix]
        # Run the formatter.
        - id: ruff-format
ci:  # https://pre-commit.ci/
    autoupdate_schedule: monthly
