# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

mkdocs:
  configuration: mkdocs.yaml

conda:
  environment: envs/docs.yaml
