name: euro-calliope
channels:
    - conda-forge
    - gurobi
dependencies:
    - python=3.7
    - gurobi=8.1.1
    - calliope=0.6.5
    - pyomo=5.6.8 # to avoid https://github.com/calliope-project/calliope/issues/309
