# A simple config to allow for quick test runs of the workflow. It builds on `./default.yaml`.
quality-control:
    hydro:
        scale-phs-according-to-geth-et-al: True # switched on to test the Geth scaling
sea-connections:
    continental: []
    national: []
    regional: []
scope:
    spatial:
        countries:
            - "Germany"
        bounds:
            x_min: 5.86
            x_max: 15.04
            y_min: 47.27
            y_max: 55.05
    temporal:
        first-year: 2015
        final-year: 2016
shapes: # This config must be consistent with data from https://doi.org/10.5281/zenodo.3244985.
    continental:
        Germany: nuts0
    national:
        Germany: nuts0
    regional:
        Germany: gadm1


