name: default
channels:
    - conda-forge
dependencies:
    - python=3.9
    - ipython=7.21.0
    - ipdb=0.13.13
    - numpy=1.20.2
    - pandas=1.2.3
    - xlrd=2.0.1
    - openpyxl=3.0.7
    - pycountry=18.12.8
    - jinja2=2.11.3
    - pip=21.0.1
    - xarray=0.17.0
    - netCDF4=1.5.6
    - hdf5=1.10
    - libnetcdf=4.8.0
    - pip:
        - -e ./lib
        - styleframe==4.2
