name: default
channels:
    - conda-forge
dependencies:
    - python=3.8
    - ipython=7.21.0
    - numpy=1.20.2
    - pandas=1.2.3
    - pycountry=18.12.8
    - jinja2=2.11.3
    - pip=21.0.1
    - pip:
        - -e ../../lib
