name: Tests of eurocalliopelib and scripts

on: [push, pull_request]

jobs:
    test:
        name: Run tests
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash -l {0}
        steps:
            - uses: actions/checkout@v2
            - name: Setup conda environment
              uses: conda-incubator/setup-miniconda@v2
              with:
                auto-update-conda: true
                python-version: 3.8
                activate-environment: test-eurocalliope
                environment-file: test-requirements.yaml
            - name: Test with pytest
              run: |
                pytest
